In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
arr2 = np.array([5,7,9,2,5,8,1,0,5,8])
arr2

array([5, 7, 9, 2, 5, 8, 1, 0, 5, 8])

In [9]:
np.maximum(arr,arr2)

array([5, 7, 9, 3, 5, 8, 6, 7, 8, 9])

In [10]:
arr2 = np.random.randn(7) * 5
arr2

array([-3.03798064,  1.20193461, -6.04572167,  3.5839351 , -0.4475563 ,
        1.35972138,  0.18494474])

In [11]:
rem,whole = np.modf(arr2)

In [12]:
rem

array([-0.03798064,  0.20193461, -0.04572167,  0.5839351 , -0.4475563 ,
        0.35972138,  0.18494474])

In [13]:
whole

array([-3.,  1., -6.,  3., -0.,  1.,  0.])

In [14]:
#Linear Algebra

In [15]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])

In [16]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [18]:
x@y

array([[ 28,  64],
       [ 67, 181]])

In [19]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [20]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [21]:
from numpy.linalg import inv

In [27]:
a=x.dot(y)
a


array([[ 28,  64],
       [ 67, 181]])

In [26]:
inv(a)

array([[ 0.23205128, -0.08205128],
       [-0.08589744,  0.03589744]])

In [29]:
b=np.array([[2,4],[1,2]])
b

array([[2, 4],
       [1, 2]])

In [31]:
inv(b) #Not possible because determinant of b is zero

LinAlgError: Singular matrix

In [33]:
c = np.random.randn(5,5)
c

array([[-1.31955385, -0.53945192,  0.47722706,  0.57317429,  0.82279788],
       [-1.77352514,  0.93708962,  1.43981645,  1.08811346, -0.29363995],
       [ 0.31997234,  1.32436507,  0.25359257,  0.50996079,  1.39375116],
       [-1.63311136,  0.67565996, -1.20295844,  0.09784418, -0.12870303],
       [ 0.25113518,  0.91605158,  0.11634238,  1.04278931, -0.52743453]])

In [34]:
mat = c.T.dot(c)
mat

array([[ 7.71911769, -1.39973113, -1.10835211, -2.42086692, -0.04125746],
       [-1.39973113,  4.21875506,  0.72142992,  2.40719231,  0.55669178],
       [-1.10835211,  0.72142992,  3.82577082,  1.97315831,  0.41678013],
       [-2.42086692,  2.40719231,  1.97315831,  2.86956271,  0.30025552],
       [-0.04125746,  0.55669178,  0.41678013,  0.30025552,  3.00051473]])

In [35]:
#Pandas

In [36]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [37]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [38]:
s1.values

array([1, 2, 3, 4, 5])

In [39]:
s1.dtype

dtype('int64')

In [40]:
s2 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [41]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [42]:
s1[3]

np.int64(4)

In [44]:
s1[1:3]

1    2
2    3
dtype: int64

In [45]:
s1>2

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [47]:
s1[s1>2]

2    3
3    4
4    5
dtype: int64

In [48]:
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [49]:
s2['c']

np.int64(3)

In [52]:
s2['b':'f']

b    2
c    3
d    4
e    5
dtype: int64

In [53]:
print(type(s2))

<class 'pandas.core.series.Series'>


In [54]:
s2.shape

(5,)

In [55]:
s2.size

5